language: python
python:
    - "2.2"
    - "2.4"
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.1.5"
    - "3.2.3"
    - "3.3.0"
install:
    - python setup.py install
script:
    - python mimic_test.py
